### PR TITLE
Fix sentence and remove existing action comments

### LINKED ISSUE #2056: Update message when adding harden runner
It is missing an `a`. It should be `egress-policy: audit # TODO: change to 'egress-policy: block' after a couple of runs`

### LINKED ISSUE #2064: Replace tag if already exists when pinning Action
See this case: 
https://github.com/deislabs/ratify/pull/755#pullrequestreview-1373868550

### PR DESCRIPTION
**Pull request by arjundashrath**
closes #2056 
closes #2064

@varunsh-coder I rebased it. This PR has both the bug fixes

### CODE REVIEW

File: remediation/workflow/pin/pinactions.go [hunk 1]
```diff
@@ -76,6 +76,13 @@ func PinAction(action, inputYaml string) (string, bool) {
 	pinnedAction := fmt.Sprintf("%s@%s # %s", leftOfAt[0], commitSHA, tagOrBranch)
 	updated = !strings.EqualFold(action, pinnedAction)
 	inputYaml = strings.ReplaceAll(inputYaml, action, pinnedAction)
+	stringParts := strings.SplitN(inputYaml, pinnedAction, 2)
```
Comment (varunsh-coder) [inline remediation/workflow/pin/pinactions.go:79]: @Devils-Knight can you please review this code? I think you had worked on this code recently, so just review this logic once. Also confirm if this change is on the latest from `main`.

**Comment by Devils-Knight** [comment]
@varunsh-coder the above logic looks fine to me and also the changes are on latest with reference to main.

**Comment by arjundashrath** [comment]
@varunsh-coder added a more complex test case
